version: 2

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: GITHUB

jobs:
  build:
    machine:
      docker:
        - image: alpine:3.4
          environment:
            DATABASE_URL: postgres://127.0.0.1:5432
            RAILS_ENV: test
        - image: circleci/postgres:9.6.2-alpine
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - run: mkdir -p /tmp/artifacts
      - run:
          name: build_image
          command: make build
      - run:
          name: brakeman
          command: make brakeman
      - run:
          name: rubocop
          command: make rubocop
