on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
   - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.7
   
    - uses: actions/checkout@v2   
    - uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true 
    - name: Build 
      run: |
          gem install bundler -v '1.17.3'
          bundle install
    - name: Unit test
      run: |
        bundle exec rake test:units  
    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: coverage/coverage.json
    - name: see current carpet
      run: |
          cd coverage
          ls -a 
   
  sonarcloud:
    needs: build-head 
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v2
      with:
          name: result
    - name: Current path
      run: |
          ls -a
          pwd
        
    - name: send slack message
      run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#qa-process\", \"username\": \"webhookbot\", \"text\": \"Build complete...\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}




  





